apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/13013SwagR/hello-world
    targetRevision: 1.28.1
    path: ./chart/
    helm:
      valueFiles:
      - "values.yaml"
      - "staging/values.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hello-world-dev