apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/13013SwagR/hello-world-env-state
    targetRevision: main
    path: ./argocd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd